EXT_FUNC(PFNGLGENVERTEXARRAYSPROC, glGenVertexArrays);
EXT_FUNC(PFNGLBINDVERTEXARRAYPROC, glBindVertexArray);
EXT_FUNC(PFNGLVERTEXATTRIBPOINTERPROC, glVertexAttribPointer);
EXT_FUNC(PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray);
EXT_FUNC(PFNGLDELETEVERTEXARRAYSPROC, glDeleteVertexArrays);

EXT_FUNC(PFNGLGENBUFFERSPROC, glGenBuffers);
EXT_FUNC(PFNGLBINDBUFFERPROC, glBindBuffer);
EXT_FUNC(PFNGLBUFFERDATAPROC, glBufferData);
EXT_FUNC(PFNGLDELETEBUFFERSPROC, glDeleteBuffers);

EXT_FUNC(PFNGLCREATESHADERPROC, glCreateShader);
EXT_FUNC(PFNGLSHADERSOURCEPROC, glShaderSource);
EXT_FUNC(PFNGLCOMPILESHADERPROC, glCompileShader);
EXT_FUNC(PFNGLGETSHADERIVPROC, glGetShaderiv);
EXT_FUNC(PFNGLGETSHADERINFOLOGPROC, glGetShaderInfoLog);

EXT_FUNC(PFNGLCREATEPROGRAMPROC, glCreateProgram);
EXT_FUNC(PFNGLATTACHSHADERPROC, glAttachShader);
EXT_FUNC(PFNGLLINKPROGRAMPROC, glLinkProgram);
EXT_FUNC(PFNGLUSEPROGRAMPROC, glUseProgram);
EXT_FUNC(PFNGLGETPROGRAMIVPROC, glGetProgramiv);
EXT_FUNC(PFNGLGETPROGRAMINFOLOGPROC, glGetProgramInfoLog);
EXT_FUNC(PFNGLUNIFORM1FPROC, glUniform1f);
EXT_FUNC(PFNGLUNIFORM2FPROC, glUniform2f);
